version: "3.8"

services:

  nats:
    image: nats-streaming:alpine
    container_name: "natscont"
    ports:
      - "4222:4222"
    restart: always
    
  
  db:
    image: postgres:14.5-alpine
    container_name: "pgdb"
    ports:
      - "5432:5432"
    restart: always
    environment:
      POSTGRES_PASSWORD: pass
      POSTGRES_USER: user
      POSTGRES_DB: db
    volumes:
      - ./repos/sql-init/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./repos/pg_data:/var/lib/postgresql/data
  go_service:
    container_name: go_service
    build: .
    entrypoint: /main
    depends_on:
      - db
      - nats
    restart: always
    ports:
      - "8080:8080"
 
